name: simple work flow
'on': push
jobs:
  cool_job:
    runs-on: ubuntu-latest
    steps:
      - name: Run a simple echo
        run: ls
      - name: reading
        run: actions/checkout@V3
      - name: checking
        run: ls
        
